=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-farmanimal-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/FarmAnimal.json",
  "title": "FarmAnimal",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "nationalID": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "nullable": true,
      "maxLength": 100
    },
    "description": {
      "type": "string",
      "nullable": true
    },
    "hasAgriParcel": {
      "type": "string",
      "format": "uuid"
    },
    "sex": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SexEnum"
        }
      ],
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "isCastrated": {
      "type": "boolean"
    },
    "species": {
      "type": "string",
      "maxLength": 255
    },
    "breed": {
      "type": "string",
      "nullable": true,
      "maxLength": 255
    },
    "birthdate": {
      "type": "string",
      "format": "date-time"
    },
    "isMemberOfAnimalGroup": {
      "$ref": "#/components/schemas/FarmAnimalGroupSerializerField"
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusEnum"
        }
      ],
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "invalidatedAtTime": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "dateModified": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    }
  },
  "required": [
    "birthdate",
    "dateCreated",
    "dateModified",
    "hasAgriParcel",
    "id",
    "invalidatedAtTime",
    "species"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-farmanimal-example.json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "nationalID": "example_onalID",
  "name": "example_l-name",
  "description": "example_iption",
  "hasAgriParcel": "550e8400-e29b-41d4-a716-446655440000",
  "sex": "example_al-sex",
  "isCastrated": true,
  "species": "example_pecies",
  "breed": "example_-breed",
  "birthdate": "2024-06-15T12:00:00Z",
  "isMemberOfAnimalGroup": "example_lGroup",
  "status": "example_status",
  "invalidatedAtTime": "2024-06-15T12:00:00Z",
  "dateCreated": "2024-06-15T12:00:00Z",
  "dateModified": "2024-06-15T12:00:00Z"
}
