=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-agriculturalmachine-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/AgriculturalMachine.json",
  "title": "AgriculturalMachine",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "name": {
      "type": "string",
      "maxLength": 100
    },
    "description": {
      "type": "string",
      "nullable": true
    },
    "hasAgriParcel": {
      "type": "string",
      "format": "uuid"
    },
    "purchase_date": {
      "type": "string",
      "format": "date"
    },
    "manufacturer": {
      "type": "string",
      "maxLength": 255
    },
    "model": {
      "type": "string",
      "maxLength": 255
    },
    "seria_number": {
      "type": "string",
      "maxLength": 255
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusEnum"
        }
      ],
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "invalidatedAtTime": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "dateModified": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    }
  },
  "required": [
    "dateCreated",
    "dateModified",
    "hasAgriParcel",
    "id",
    "invalidatedAtTime",
    "manufacturer",
    "model",
    "name",
    "purchase_date",
    "seria_number"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-agriculturalmachine-example.json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "name": "example_e-name",
  "description": "example_iption",
  "hasAgriParcel": "550e8400-e29b-41d4-a716-446655440000",
  "purchase_date": "example_e_date",
  "manufacturer": "example_cturer",
  "model": "example_-model",
  "seria_number": "example_number",
  "status": "example_status",
  "invalidatedAtTime": "2024-06-15T12:00:00Z",
  "dateCreated": "2024-06-15T12:00:00Z",
  "dateModified": "2024-06-15T12:00:00Z"
}
