=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-farmparcel-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/FarmParcel.json",
  "title": "FarmParcel",
  "type": "object",
  "properties": {
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusEnum"
        }
      ],
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "deleted_at": {
      "type": "string",
      "format": "date-time",
      "nullable": true
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "updated_at": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "identifier": {
      "type": "string",
      "maxLength": 255
    },
    "description": {
      "type": "string",
      "nullable": true
    },
    "validFrom": {
      "type": "string",
      "format": "date-time"
    },
    "validTo": {
      "type": "string",
      "format": "date-time"
    },
    "area": {
      "type": "string",
      "format": "decimal",
      "pattern": "^-?\\d{0,13}(?:\\.\\d{0,2})?$"
    },
    "hasIrrigationFlow": {
      "type": "string",
      "format": "decimal",
      "pattern": "^-?\\d{0,13}(?:\\.\\d{0,2})?$",
      "nullable": true
    },
    "category": {
      "type": "string"
    },
    "inRegion": {
      "type": "string",
      "nullable": true
    },
    "hasToponym": {
      "type": "string",
      "nullable": true
    },
    "isNitroArea": {
      "type": "boolean"
    },
    "isNatura2000Area": {
      "type": "boolean"
    },
    "isPdopgArea": {
      "type": "boolean"
    },
    "isIrrigated": {
      "type": "boolean"
    },
    "isCultivatedInLevels": {
      "type": "boolean"
    },
    "isGroundSlope": {
      "type": "boolean"
    },
    "depiction": {
      "type": "string",
      "format": "uri",
      "nullable": true,
      "maxLength": 500
    },
    "hasGeometry": {
      "$ref": "#/components/schemas/GeometrySerializerField"
    },
    "location": {
      "$ref": "#/components/schemas/LocationSerializerField"
    },
    "hasAgriCrop": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid"
      },
      "readOnly": true
    },
    "farm": {
      "type": "string",
      "format": "uuid"
    }
  },
  "required": [
    "category",
    "created_at",
    "farm",
    "hasAgriCrop",
    "hasGeometry",
    "hasIrrigationFlow",
    "hasToponym",
    "id",
    "identifier",
    "inRegion",
    "isCultivatedInLevels",
    "isGroundSlope",
    "isIrrigated",
    "isNatura2000Area",
    "isNitroArea",
    "isPdopgArea",
    "location",
    "updated_at",
    "validFrom",
    "validTo"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-farmparcel-example.json
{
  "status": "example_status",
  "deleted_at": "2024-06-15T12:00:00Z",
  "created_at": "2024-06-15T12:00:00Z",
  "updated_at": "2024-06-15T12:00:00Z",
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "identifier": "example_tifier",
  "description": "example_iption",
  "validFrom": "2024-06-15T12:00:00Z",
  "validTo": "2024-06-15T12:00:00Z",
  "area": "example_l-area",
  "hasIrrigationFlow": "example_onFlow",
  "category": "example_tegory",
  "inRegion": "example_Region",
  "hasToponym": "example_oponym",
  "isNitroArea": true,
  "isNatura2000Area": true,
  "isPdopgArea": true,
  "isIrrigated": true,
  "isCultivatedInLevels": true,
  "isGroundSlope": true,
  "depiction": "example_iction",
  "hasGeometry": "example_ometry",
  "location": "example_cation",
  "hasAgriCrop": [],
  "farm": "550e8400-e29b-41d4-a716-446655440000"
}
