=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-observation-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/Observation.json",
  "title": "Observation",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "activityType": {
      "type": "string",
      "format": "uuid"
    },
    "title": {
      "type": "string",
      "maxLength": 200
    },
    "details": {
      "type": "string",
      "nullable": true
    },
    "phenomenonTime": {
      "type": "string",
      "format": "date-time"
    },
    "hasEndDatetime": {
      "type": "string",
      "format": "date-time",
      "nullable": true
    },
    "hasAgriParcel": {
      "type": "string",
      "format": "uuid"
    },
    "madeBySensor": {
      "allOf": [
        {
          "$ref": "#/components/schemas/MadeBySensorField"
        }
      ],
      "nullable": true
    },
    "hasResult": {
      "$ref": "#/components/schemas/GenericQuantityValueField"
    },
    "observedProperty": {
      "type": "string"
    }
  },
  "required": [
    "activityType",
    "hasAgriParcel",
    "hasResult",
    "id",
    "observedProperty",
    "phenomenonTime"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-observation-example.json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "activityType": "550e8400-e29b-41d4-a716-446655440000",
  "title": "example_-title",
  "details": "example_etails",
  "phenomenonTime": "2024-06-15T12:00:00Z",
  "hasEndDatetime": "2024-06-15T12:00:00Z",
  "hasAgriParcel": "550e8400-e29b-41d4-a716-446655440000",
  "madeBySensor": "example_Sensor",
  "hasResult": "example_Result",
  "observedProperty": "example_operty"
}
