=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-fertilizer-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/Fertilizer.json",
  "title": "Fertilizer",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "hasCommercialName": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "nullable": true
    },
    "hasCost": {
      "type": "string",
      "format": "decimal",
      "pattern": "^-?\\d{0,8}(?:\\.\\d{0,2})?$"
    },
    "isPricePer": {
      "type": "string"
    },
    "hasActiveSubstance": {
      "type": "string"
    },
    "isTargetedTowards": {
      "type": "string"
    },
    "hasNutrientConcentration": {
      "type": "string"
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusEnum"
        }
      ],
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "dateModified": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "invalidatedAtTime": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    }
  },
  "required": [
    "dateCreated",
    "dateModified",
    "hasActiveSubstance",
    "hasCommercialName",
    "hasCost",
    "hasNutrientConcentration",
    "id",
    "invalidatedAtTime",
    "isPricePer",
    "isTargetedTowards"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-fertilizer-example.json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "hasCommercialName": "example_alName",
  "description": "example_iption",
  "hasCost": "example_asCost",
  "isPricePer": "example_icePer",
  "hasActiveSubstance": "example_stance",
  "isTargetedTowards": "example_owards",
  "hasNutrientConcentration": "example_ration",
  "status": "example_status",
  "dateCreated": "2024-06-15T12:00:00Z",
  "dateModified": "2024-06-15T12:00:00Z",
  "invalidatedAtTime": "2024-06-15T12:00:00Z"
}
