=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-farmcrop-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/FarmCrop.json",
  "title": "FarmCrop",
  "type": "object",
  "properties": {
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusEnum"
        }
      ],
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "invalidatedAtTime": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "dateModified": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "name": {
      "type": "string",
      "maxLength": 100
    },
    "description": {
      "type": "string",
      "nullable": true
    },
    "hasAgriParcel": {
      "type": "string",
      "format": "uuid"
    },
    "cropSpecies": {
      "$ref": "#/components/schemas/CropSpeciesSerializerField"
    },
    "growth_stage": {
      "type": "string",
      "nullable": true,
      "maxLength": 255
    }
  },
  "required": [
    "cropSpecies",
    "dateCreated",
    "dateModified",
    "hasAgriParcel",
    "id",
    "invalidatedAtTime",
    "name"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-farmcrop-example.json
{
  "status": "example_status",
  "invalidatedAtTime": "2024-06-15T12:00:00Z",
  "dateCreated": "2024-06-15T12:00:00Z",
  "dateModified": "2024-06-15T12:00:00Z",
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "name": "example_p-name",
  "description": "example_iption",
  "hasAgriParcel": "550e8400-e29b-41d4-a716-446655440000",
  "cropSpecies": "example_pecies",
  "growth_stage": "example__stage"
}
