=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-farm-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/Farm.json",
  "title": "Farm",
  "type": "object",
  "properties": {
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusEnum"
        }
      ],
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "deleted_at": {
      "type": "string",
      "format": "date-time",
      "nullable": true
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "updated_at": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "administrator": {
      "type": "string"
    },
    "telephone": {
      "type": "string"
    },
    "vatID": {
      "type": "string"
    },
    "hasAgriParcel": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid"
      },
      "readOnly": true
    },
    "contactPerson": {
      "$ref": "#/components/schemas/ContactPersonField"
    },
    "address": {
      "$ref": "#/components/schemas/AddressField"
    }
  },
  "required": [
    "address",
    "administrator",
    "contactPerson",
    "created_at",
    "description",
    "hasAgriParcel",
    "id",
    "name",
    "telephone",
    "updated_at",
    "vatID"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-farm-example.json
{
  "status": "example_status",
  "deleted_at": "2024-06-15T12:00:00Z",
  "created_at": "2024-06-15T12:00:00Z",
  "updated_at": "2024-06-15T12:00:00Z",
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "name": "example_m-name",
  "description": "example_iption",
  "administrator": "example_trator",
  "telephone": "example_ephone",
  "vatID": "example_-vatID",
  "hasAgriParcel": [],
  "contactPerson": "example_Person",
  "address": "example_ddress"
}
