=== api-evangelist/agstack/json-schema/agstack-openagri-farm-calendar-alert-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agstack.org/schemas/Alert.json",
  "title": "Alert",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "readOnly": true
    },
    "activityType": {
      "type": "string",
      "format": "uuid"
    },
    "title": {
      "type": "string",
      "maxLength": 200
    },
    "details": {
      "type": "string",
      "nullable": true
    },
    "severity": {
      "$ref": "#/components/schemas/SeverityEnum"
    },
    "hasAgriParcel": {
      "type": "string",
      "format": "uuid"
    },
    "validFrom": {
      "type": "string",
      "format": "date-time"
    },
    "validTo": {
      "type": "string",
      "format": "date-time"
    },
    "dateIssued": {
      "type": "string",
      "format": "date-time",
      "readOnly": true,
      "nullable": true
    },
    "quantityValue": {
      "$ref": "#/components/schemas/ObservationQuantityValueField"
    },
    "relatedObservation": {
      "type": "string",
      "format": "uuid",
      "nullable": true
    }
  },
  "required": [
    "activityType",
    "dateIssued",
    "hasAgriParcel",
    "id",
    "relatedObservation",
    "validFrom",
    "validTo"
  ]
}

=== api-evangelist/agstack/examples/agstack-openagri-farm-calendar-alert-example.json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "activityType": "550e8400-e29b-41d4-a716-446655440000",
  "title": "example_-title",
  "details": "example_etails",
  "severity": "example_verity",
  "hasAgriParcel": "550e8400-e29b-41d4-a716-446655440000",
  "validFrom": "2024-06-15T12:00:00Z",
  "validTo": "2024-06-15T12:00:00Z",
  "dateIssued": "2024-06-15T12:00:00Z",
  "quantityValue": "example_yValue",
  "relatedObservation": "550e8400-e29b-41d4-a716-446655440000"
}
